### ISSUE TITLE
[BUG] v1.0.0 incompatible with exist 5.3.0

### ISSUE THREAD

**Issue by line-o** [eXist-db/github-xq#1]
**Describe the bug**

github-xq-1.0.0.xar cannot be uploaded using the package manager.
An error is thrown that expath-http-client was not found in the public package repository. 

> Failed to install dependency from http://exist-db.org/exist/apps/public-repo/find?name=http%3A%2F%2Fexpath.org%2Fns%2Fhttp-client&processor=5.3.0: http://exist-db.org/exist/apps/public-repo/find?name=http%3A%2F%2Fexpath.org%2Fns%2Fhttp-client&processor=5.3.0

This is very likely because the expath-http-client library is now bundled with exist-db.

**Expected behavior**

That the XAR can be uploaded using the package manager.

**To Reproduce**

- open dashboard
- got package manager
- upload XAR

**Context (please always complete the following information):**
 - OS: macOS 15.7.1
 - eXist-db Version: 5.3.0
 - Java Version: AdoptOpenJDK 8
-  App Version: 1.0.0

**Additional context**
- How is eXist-db installed? DMG
- Any custom changes in e.g. `conf.xml`? none

**Comment by wsalesky** [comment]
Resolved with: https://github.com/eXist-db/github-xq/pull/2
